### ISSUE TITLE
forjj create fails to create relationship between github/jenkins

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#209]
When forjj do not make this relationship several piece of the code will fail, like:
- [x] no webhook created. **Normal use case. Nothing to do**
- [ ] limit of github API reached
- [ ] seedjob missing github plugin.

**Comment by clarsonneur** [comment]
Webhook cannot be created when the jenkins is localhost.

To see webhook working, Jenkins web service MUST be accessible to github service.

I'm reducing the priority of this issue to normal.

**Comment by clarsonneur** [comment]
I'm wondering if this issue is still relevant... @uggla, do you have feedback?

**Comment by uggla** [comment]
Hello @clarsonneur , to my mind this is working now, as far as we set the jenkins server name into Forjfile.

**Comment by clarsonneur** [comment]
ok. Closing it.
