### ISSUE TITLE
Re-implement forjj update

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#40]
forjj update get the Forjfile located in the repository (with .forj-workspace) to update source code through all plugins.

Forjfile is not updated anymore.

If some update requires removal of things, we need to detect it and ask maintain to do the real deletion, ie ensure deleted.
Same thing about rename.

Update can be done, if we find a valid repo. If no workspace exist, create it.
We may need to provide secrets (cli/env/interactive)
We could in future get those creds from a service instead (vault)

Steps:
- [ ] forjj
- [x] plugin github
- [x] plugin jenkins

**Comment by clarsonneur** [comment]
@uggla Latest forjj has been published and is usable for create/update and maintain !!!

**Comment by uggla** [comment]
@clarsonneur 👍 🥇
