### ISSUE TITLE
Coredump when projects refer to an unknown repository

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#43]
The issue has been detected as well by @uggla.

**Comment by clarsonneur** [comment]
@uggla I found the similar coredump you found.

All related to repo.go, which was not testing an empty repository. So, the fix is quite important.
I have those listed here. You may found some others, but at least, now, I'm fixing them to remove a lot of possible coredump.

**Comment by uggla** [comment]
👍
